### ISSUE TITLE
To do list

### ISSUE THREAD

**Issue by cjdell** [AllAboutCode/EduBlocks#1]
- Install instructions on website need to be updated (use curl instead)
- ESC to hide console not obvious
- Clear console on run, don't show output of previous run
- Install time needs to be less (use Electron pre-built maybe?)
- Future ideas: Run on PC? Try out live on web?

**Comment by JoshuaLowe1002** [comment]
AUTOMATIC REPLY
=============
The All About Code has reviewed this issue and labelled it as 'Enhancments' and has assigned @cjdell & @joshualowe1002 to fulfil the changes to the software. Any further issues regarding this should be put as a reply to this issue or alternatively another issue if it is not related.

**Comment by JoshuaLowe1002** [comment]
Forgot to close this one
