### ISSUE TITLE
Problem with lists?

### ISSUE THREAD

**Issue by vuod** [AllAboutCode/EduBlocks#104]
I've tried this in Python 3 mode. New sessions of Chromium, Firefox and Opera.

Add the first list block (list = [1, 2, 3, 4]). Variable = list
Switch to the editor. list2 = [1, 2, 3, 4]. Variable = list2

A debutant will try to add a print(list) block and will get : <class 'list'> in trinket

It works with print(list2) but the block still shows Variable = list.

Thanks.

**Comment by JoshuaLowe1002** [comment]
Yeah, sorry, you must use List1 etc as List is a reserved word in Python. I should change that block!
