### ISSUE TITLE
ws2811x (neopixel) block

### ISSUE THREAD

**Issue by anwarbashir** [AllAboutCode/EduBlocks#113]
I am trying to implement blocks to control neoixels. I have a python3 implementation working locally but when I run from edublocks I get error, see below. I have tried to change the permissions for /dev/mem to no avail. Not sure what user the program runs as? Could you advise? Thanks.

[Starting]

{'r': 13, 'f': 15, 'e': 11}
{'r': 18, 'f': 16, 'e': 22}
Can't open /dev/mem: Permission denied
Traceback (most recent call last):
  File "/home/pi/.edublocks/output.py", line 160, in <module>
    strip.begin()
  File "/usr/local/lib/python3.5/dist-packages/rpi_ws281x-4.2.3-py3.5-linux-armv7l.egg/rpi_ws281x/rpi_ws281x.py", line 131, in begin
    raise RuntimeError('ws2811_init failed with code {0} ({1})'.format(resp, str_resp))
RuntimeError: ws2811_init failed with code -5 (mmap() failed)

**Comment by JoshuaLowe1002** [comment]
Hi, Neopixels on the Pi (If I remember correctly) require root access from the python shell. I imagine (this is a guess) you'd need to run EduBlocks as root.

**Comment by anwarbashir** [comment]
Hi,

Thank you for your reply. 

Yes, after some futher checks the rpi-ws281x-python library requires root access so I need EduBlocks to run the code/library as root. I know this is a security issue, but is this possible? If not is there some workaround that you could suggest?
