### ISSUE TITLE
Hello i am unable to install the build on web server centos ...

### ISSUE THREAD

**Issue by armornet** [AllAboutCode/EduBlocks#114]
I am getting error on 
cd ../server
yarn

and if i skip that and proceed then again i get 
"Please do not run me as root"

when use 
./tarball-create.sh

Please guide as i want to have edublocks on my own server

**Comment by J0ful** [comment]
i run edublocks in raspi, maybe you could try this:
if it was an access error, you can change the file access, or use 'sudo yarn'.

**Comment by armornet** [comment]
I am looking for a workaround how to install on my centos server so that i an access it online.. any help will be great

**Comment by JoshuaLowe1002** [comment]
Replied to you via email
