### ISSUE TITLE
Adding library in Python3 

### ISSUE THREAD

**Issue by ViniciusAg** [AllAboutCode/EduBlocks#115]
Hi Joshua,
I wanna add new libraries using Python3, but I wasn't able to do it, could you please tell me how to do it?

**Comment by niutech** [comment]
Here is an old tutorial on [how to add a library to EduBlocks](https://web.archive.org/web/20180901155329/https://allaboutcode.co.uk/2018/07/30/adding-a-library-to-edublocks-on-the-raspberry-pi/).
