### ISSUE TITLE
Python3 still consuming 100% CPU after script has finished

### ISSUE THREAD

**Issue by PeterOGB** [AllAboutCode/EduBlocks#13]
After a script has finished, and the output display closed with "ESC", there is still a python3 process running that is consuming 100% of one CPU core.  This should  have been stopped once the script finished.

**Comment by JoshuaLowe1002** [comment]
Found the issue. In order for sonic pi live loops to work, the python 3 process continues running I shall work on fixing this bug.

**Comment by JoshuaLowe1002** [comment]
Added in new version: curl -sSL get.edublocks.org | bash
