### ISSUE TITLE
Move the from turtle import * block to the imports section

### ISSUE THREAD

**Issue by amos1969** [AllAboutCode/EduBlocks#139]
Currently, the `from turtle import *` block lives in the Turtle section (tab?) along with all of the other blocks specific to the Turtle module. 

The Processing and PyGal imports are both included in the imports section, for consistency I suggest moving `from turtle import *` into that main imports section.

**Comment by JoshuaLowe1002** [comment]
Sure! That was on the list of things to look into for the August release. 

Will make sure i get round to doing it.

**Comment by JoshuaLowe1002** [comment]
This has now been fixed in the new version https://staging.edublocks.org
