### ISSUE TITLE
Cannot add extensions

### ISSUE THREAD

**Issue by Bhavithiran97** [AllAboutCode/EduBlocks#140]
Hi, 
I had followed this [link](https://docs.edublocks.org/developer-docs/create-a-micro-bit-extension#step-6-create-a-simple-text-block) to add custom extensions for micro:bit
In order to test I have then cloned my own copy and tried the steps, but I receive some errors
```
What is the name of your extension?
edubit
Where are your files located? (Provide Full Path + forward slash at the end)
C:/Users/Cytron lenovo/Edublock/edubit/
cp: target 'ui/src/blocks/microbit/edubit/definitions.ts' is not a directory
cp: target 'ui/src/blocks/microbit/edubit/generators.ts' is not a directory
cp: target 'ui/src/blocks/microbit/edubit/toolbox.xml' is not a directory
cp: target 'ui/images/edubit.png' is not a directory
cp: target 'ui/images/edubit-icon.png' is not a directory
cp: target 'ui/src/blocks/microbit/edubit/edubit.py' is not a directory
Completed!
```

Can you advise what did I done wrongly ? Thanks

**Comment by JoshuaLowe1002** [comment]
Hi!

It looks like you are running this on Windows? The guide suggests that if you are creating an extensions on a windows computer you do it through Ubuntu on Windows :)

**Comment by Bhavithiran97** [comment]
Yes I am using Ubuntu on Windows. `python3 extensions.py` is run on windows subsystem for linux

**Comment by Bhavithiran97** [comment]
Hi, thanks for the advice. I can succesfully run `extension.py` now, but my extension is not shown on localhost:8081

**Comment by Bhavithiran97** [comment]
Thanks, issue solved
