### ISSUE TITLE
Add integer division to the basic arithmetic block

### ISSUE THREAD

**Issue by amos1969** [AllAboutCode/EduBlocks#142]
In the basic arithmetic block at the top of the Math section:

![image](https://user-images.githubusercontent.com/241461/89192753-e44baa80-d59c-11ea-95b0-fb8d3901e750.png)

the drop down provides +. -, /, % and * but misses out // for doing integer division.

Adding this option in would mean that users didn't have to resort to typing that in themselves.

**Comment by JoshuaLowe1002** [comment]
Will add into the beta
