### ISSUE TITLE
Raspberry Pi Bullseye 

### ISSUE THREAD

**Issue by pilover1000** [AllAboutCode/EduBlocks#162]
Hello I am trying to install edublocks but I get an error not found. 

Here are my logs: 

Downloading package...
URL transformed to HTTPS due to an HSTS policy
--2022-02-11 16:20:39--  https://edublocks.org/downloads/edublocks-armv6l.tar.xz
Resolving edublocks.org (edublocks.org)... 2606:4700:3035::ac43:ab85, 2606:4700:3033::6815:57f4, 172.67.171.133, ...
Connecting to edublocks.org (edublocks.org)|2606:4700:3035::ac43:ab85|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/x-xz]
Saving to: ‘edublocks-armv6l.tar.xz’

edublocks-armv6l.ta     [          <=>       ]  11.70M  5.79MB/s    in 2.0s    

2022-02-11 16:20:42 (5.79 MB/s) - ‘edublocks-armv6l.tar.xz’ saved [12263800]

Extracting package...

Running install dependencies script...
Changing Chromium preferences to ask for directory upon saving a download...
Installing EduBlocks Python Libraries..
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Requirement already satisfied: python-sonic in /usr/local/lib/python3.9/dist-packages (0.4.3)
Requirement already satisfied: blinkt in /usr/lib/python3/dist-packages (0.1.2)
Requirement already satisfied: explorerhat in /usr/lib/python3/dist-packages (0.4.2)
Requirement already satisfied: ipython==6.0.0 in /usr/local/lib/python3.9/dist-packages (6.0.0)
Requirement already satisfied: cs20-microbitio in /usr/local/lib/python3.9/dist-packages (0.2)
Requirement already satisfied: pickleshare in /usr/lib/python3/dist-packages (from ipython==6.0.0) (0.7.5)
Requirement already satisfied: jedi>=0.10 in /usr/lib/python3/dist-packages (from ipython==6.0.0) (0.18.0)
Requirement already satisfied: pygments in /usr/lib/python3/dist-packages (from ipython==6.0.0) (2.7.1)
Requirement already satisfied: decorator in /usr/lib/python3/dist-packages (from ipython==6.0.0) (4.4.2)
Requirement already satisfied: setuptools>=18.5 in /usr/lib/python3/dist-packages (from ipython==6.0.0) (52.0.0)
Requirement already satisfied: pexpect in /usr/lib/python3/dist-packages (from ipython==6.0.0) (4.8.0)
Requirement already satisfied: simplegeneric>0.8 in /usr/local/lib/python3.9/dist-packages (from ipython==6.0.0) (0.8.1)
Requirement already satisfied: prompt-toolkit<2.0.0,>=1.0.4 in /usr/local/lib/python3.9/dist-packages (from ipython==6.0.0) (1.0.18)
Requirement already satisfied: traitlets>=4.2 in /usr/lib/python3/dist-packages (from ipython==6.0.0) (5.0.5)
Requirement already satisfied: six>=1.9.0 in /usr/lib/python3/dist-packages (from prompt-toolkit<2.0.0,>=1.0.4->ipython==6.0.0) (1.16.0)
Requirement already satisfied: wcwidth in /usr/lib/python3/dist-packages (from prompt-toolkit<2.0.0,>=1.0.4->ipython==6.0.0) (0.1.9)
Requirement already satisfied: RPi.GPIO in /usr/lib/python3/dist-packages (from blinkt) (0.7.0)
Requirement already satisfied: cap1xxx in /usr/lib/python3/dist-packages (from explorerhat) (0.1.3)
Requirement already satisfied: python-osc in /usr/local/lib/python3.9/dist-packages (from python-sonic) (1.8.0)

Running install script...
Copying the icon...
Making the program visible in the menu...
Creating symlinks...
--2022-02-11 16:20:50--  http://app.edublocks.org/dist/main.js
Resolving app.edublocks.org (app.edublocks.org)... 40.118.40.109
Connecting to app.edublocks.org (app.edublocks.org)|40.118.40.109|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://app.edublocks.org/dist/main.js [following]
--2022-02-11 16:20:51--  https://app.edublocks.org/dist/main.js
Connecting to app.edublocks.org (app.edublocks.org)|40.118.40.109|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2022-02-11 16:20:51 ERROR 404: Not Found.

Removing temp download...

Removing temp extract...
--2022-02-11 16:20:51--  http://app.edublocks.org/picnic/picnic.css
Resolving app.edublocks.org (app.edublocks.org)... 40.118.40.109
Connecting to app.edublocks.org (app.edublocks.org)|40.118.40.109|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://app.edublocks.org/picnic/picnic.css [following]
--2022-02-11 16:20:51--  https://app.edublocks.org/picnic/picnic.css
Connecting to app.edublocks.org (app.edublocks.org)|40.118.40.109|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2022-02-11 16:20:52 ERROR 404: Not Found.

**Comment by langius** [comment]
I too am wondering how to successfully add edublocks to a raspberry pi running buster or bullseye. The curl bash method seems to no longer work. It does not work in chromium either.

**Comment by JoshuaLowe1002** [comment]
Whoops sorry @langius, please try again. I've just tried on a new install and got EduBlocks connect installed successfully.
