### ISSUE TITLE
Code I would like to work with EduBlocks

### ISSUE THREAD

**Issue by RaspiKidd** [AllAboutCode/EduBlocks#19]
Hey Guys, great work so far. loving exploring the new features.

I have python code in this repo [Python Code Snippets](https://github.com/RaspiKidd/Python/tree/master/CodeSnippets/GetWorkingWithEduBlocks) That I use quite a bit at jams. would love to get them working with EduBlocks if possible.

Thanks

Kerry

**Comment by JoshuaLowe1002** [comment]
Will take a look

**Comment by JoshuaLowe1002** [comment]
Added all the stuff for these to work
