### ISSUE TITLE
I really like edublocks, but I can not install successfully under different operating systems.

### ISSUE THREAD

**Issue by chessgogogo** [AllAboutCode/EduBlocks#26]
Dear Joshua Lowe @ joshualowe1002:

Hello there!

I come from China, I was a primary school information technology teacher, accidentally search to see edublocks,

Your work edublocks is a great work, I really like it, especially build code can interact with minecraft pi, very cool, I would like to try to experience edublocks.

However, I do not have raspberry pie.

Then I started to try installing with windows7, but did not succeed.

I tried using Mac OS again, py3 and py2.7 are working, but I still can not start edublocks.

Then I have tried to use ubuntu16.04 desktop, first installed py2 and py3, nodejs, then install edublocks, but still can not start edublocks.

Finally, I downloaded RASPBERRY PI DESKTOP, a system for the RASPBERRY PI X86 architecture, and then I installed edublocks, but I still could not start edublocks.

At the moment, I collapsed.

How can I install successfully on windows7 and Mac OS?

After all, most Chinese students use the operating system windwos7.

Can you provide a detailed installation tutorial? Such as for windows7 and Mac OS.

Thanks again to Joshua Lowe @ joshualowe1002 and your team.

Finally, I heard Joshua Lowe is a 10-year-old child, is this true? Amazing!

Sorry, I can not write English, I use google translate this. I hope you can understand.

**Comment by JoshuaLowe1002** [comment]
Hi There @chessgogogo ,

What are the chances of finding EduBlocks by mistake? 

Great to hear that more people outside the UK are discovering the program, it's exactly what I hoped for when I first started creating it over 2 years ago. I am now 13 (14 soon) so started creating it when I was about 12, people get mistaken over my age as I have had many past projects, don't worry!

Sorry to hear you have had no success installing EduBlocks. I have been working very hard over the past few months to create a web version of EduBlocks. This is near completion and we hope to have it out in the next few weeks, to keep updated with this, follow our twitter account at [@edu_blocks](http://twitter.com/edu_blocks) .

If you have any more questions, feel free to ask them here or if it is easier to do so, over on our support page at [https://support.edublocks.org](https://support.edublocks.org) .

EduBlocks is a fully community-run project, and even though I lead the project, it's thanks to our users and contributors that EduBlocks stays alive. 

Thanks,

Josh


Google translate version:

你好 @chessgogogo ，

错误地找到EduBlocks的机会有多大？

很高兴听到英国以外的更多人正在发现这个计划，这正是我2年前开始创建计划时所期望的。我现在十三岁（十四岁），十二岁左右就开始创作了，因为我已经做了很多过去的项目，所以人们会误认我的年龄，别担心！

很抱歉听说你没有成功安装EduBlocks。过去几个月，我一直在努力创建一个EduBlocks的Web版本。现在已经接近完成了，我们希望在接下来的几个星期内完成更新，并在[@edu_blocks]（http://twitter.com/edu_blocks）上关注我们的Twitter帐户。

如果您还有其他问题，请随时在此处询问，或者如果更容易，请访问我们的支持页面[https://support.edublocks.org]（https://support.edublocks.org） 。

EduBlocks是一个完全由社区运行的项目，尽管我领导这个项目，但是感谢我们的用户和贡献者，EduBlocks依然活着。

谢谢，

玩笑

**Comment by chessgogogo** [comment]
Hi There @JoshuaLowe1002

"What are the chances of finding EduBlocks by mistake?",Sorry, google translate misunderstood me.

My original meaning is: surprise An Unexpected Journey.


Thank you and your team for their contributions, and I'm really looking forward to the new version of edublocks available for windows 7. In the future, I can also provide Chinese language packs for your convenience to Chinese users.

I will continue to focus on your project and your Twitter.

**Comment by JoshuaLowe1002** [comment]
Oh yes, that would be great @chessgogogo ! I am investigating providing a language pack contribution service to be delivered very soon!

**Comment by rsrini7** [comment]
Thanks for wonderful opensource software :)

I too looking for windows support for my students who don't have interest connection. 
tried multiple ways to install in windows - all failed. is there any way that i can install in windows ?

**Comment by avvalcode** [comment]
hi, @JoshuaLowe1002 I'm also interested how I can translate blocks and add the Persian language.

**Comment by rsrini7** [comment]
Hi @JoshuaLowe1002 , any updates about edu_blocks for Windows

**Comment by JoshuaLowe1002** [comment]
Hello @rsrini7 & @avvalcode . I am working on the Windows App today :)

**Comment by JoshuaLowe1002** [comment]
Update: Windows app is created, just working on the installer now 😄 
![image](https://user-images.githubusercontent.com/25752941/40622178-263ee54e-6298-11e8-8787-ad5a30bc1ef7.png)

**Comment by avvalcode** [comment]
@JoshuaLowe1002 congratulations, any thought on translation futures? so we can use it in our native language as well.

**Comment by JoshuaLowe1002** [comment]
Yes, this is being thought of and is the next step for EduBlocks! @avvalcode

**Comment by enemali** [comment]
> **Update: Windows app is created, just working on the installer now** 

Any chance for us to test the window version, I'm from Nigeria and most our children in Nigeria uses the window operating system. 
Maybe a link to the window installer or tutorial on how to set it up on windows will be cool.
Great project , keep it up.

**Comment by Heath3827** [comment]
Is it possible to install on regular Debian/Ubuntu?

**Comment by titimoby** [comment]
@JoshuaLowe1002  can we do something to help you on the topic of using different OS?

**Comment by JoshuaLowe1002** [comment]
So the current plan is to make a version dedicated to Windows and Mac, rather than just an offline micro:bit editor, however, this is still in the works and I don't expect to see it for a bit. @titimoby

**Comment by JoshuaLowe1002** [comment]
https://github.com/AllAboutCode/EduBlocks/blob/tarball-install/README.md#full-developer-instuctions You can use those to install on any linux distro @Heath3827

**Comment by techtheory** [comment]
Joshua, you are the man! That's all.

**Comment by JoshuaLowe1002** [comment]
**So, where are we going with this then?**

The plan here is to have a generic web version for Python. This will include basic python stuff, turtle, requests (basically your standard Python stuff).

My plan with this is also to abolish the Raspberry Pi version for a link program that would connect to the web version that is similar to the new Scratch Link program, the reason for doing this is it's sort of getting abandoned development wise as the micro:bit and the new circuitpython editors are getting a lot more use than that. I hope that this will give the Pi version a refresh but at the same time give a version everyone can use, this will open edublocks up to everyone rather than those with hardware, my hope will be that you will have to install nothing unless you're using stuff like the Raspberry Pi where you will just run a program similar to Scratch Link. 

I'd like to get your feedback on this, as many people have emailed about doing this and this is what I think would be a better way to approach this. I hope by doing this, it's going to boost the popularity of this program as i feel the hardware thing is the biggest barrier to entry.

It is to be noted though, I am currently doing GCSEs so this is going to be a gradual project, not something you're going to see in 3 weeks time :)

**Comment by BjornFJohansson** [comment]
Hi, I would like to use edublocks to tech programming to my kids. I found out that their schools curriculum starts and ends with scratch and I do not really think that is enough. Problem is that I would need a windows version or an online version since I do not have any raspberry pi (yet). I understood from the exchange above that either of these are in the works?
Thanks!

**Comment by JoshuaLowe1002** [comment]
Hi @BjornFJohansson ,

Yes this is in the works, for a demo, see: https://twitter.com/all_about_code/status/1081232834537422851

**Comment by BjornFJohansson** [comment]
How is the web version coming along?

**Comment by JoshuaLowe1002** [comment]
Hey @BjornFJohansson , it's on track to be released next week.

**Comment by MagicFab** [comment]
@JoshuaLowe1002 will this new version include an emulator (for example for Microbit) like Makecode does ?

**Comment by JoshuaLowe1002** [comment]
Just replied via twitter :) @MagicFab

**Comment by MagicFab** [comment]
@JoshuaLowe1002 thanks! Not everyone is on Twitter and content there may not be up as long as here - citing you:

> It's something we're working on, but not sure if it's actually possible for us to do yet as it might involve changes in actual micropython. Watch this space though!
> 
> But you'll be able to create python programs in the web and run them directly from the browser in the new python mode on any device with a browser
>

**Comment by JoshuaLowe1002** [comment]
Hey all!

Happy to announce the browser based edublocks is now available at https://app.edublocks.org!

Hope you like it!

**Comment by ptal78** [comment]
Hi, is there any update on the windows app? And can it program micropython on the ESP32? And I've seen you do Wireless coding on the ESP32 in a video. Will this be featured any time soon?
