### ISSUE TITLE
Why no import time block

### ISSUE THREAD

**Issue by cymplecy** [AllAboutCode/EduBlocks#27]
I was testing new microbit edublocks and noticed that although there is a sleep block I couldn't see a corresponding import time.   AFAIK sleep isn't core Python - its needs time module to function

**Comment by JoshuaLowe1002** [comment]
Hey @cymplecy , in micropython. Sleep is part of the core python/imported with the microbit block. It uses milliseconds instead of seconds too. Hope this helps! :)
