### ISSUE TITLE
[request]Enhanced Duplicate

### ISSUE THREAD

**Issue by cymplecy** [AllAboutCode/EduBlocks#30]
In Scratch, duplicate will duplicate the block selected and all the ones below it
Could we have the same in Edublocks please?

Plus also have a "Duplicate this block only" 
:)

**Comment by JoshuaLowe1002** [comment]
Hi Simon!

This is a restriction in Blockly (I know it's annoying). But I shall investigate if there is a way around it 

Josh

**Comment by JoshuaLowe1002** [comment]
This is a blockly restriction and is something that is not an open feature yet, therefore, it can not be implemented to EduBlocks yet. I shall keep an eye out
