### ISSUE TITLE
Can't read Pin8

### ISSUE THREAD

**Issue by cymplecy** [AllAboutCode/EduBlocks#31]
The 4tronix bit:commander uses pins 8,12,14,15,16 as switches but I don't seem able to select them for use as digital inputs.

Is this something that can be changed in Edublocks or is it a micropython restriction?

**Comment by JoshuaLowe1002** [comment]
It's probably a micropython restriction.

Send me a copy of the python code (Click Download PY) via here or at support@edublocks.org and we will get this sorted :)

**Comment by ntoll** [comment]
Use the latest firmware. See firmware.hex in here: https://github.com/ntoll/uflash

**Comment by JoshuaLowe1002** [comment]
Hey Simon,

This was an EduBlocks bug and is now solved by allowing you to input any number you would like, this replaces the dropdown.

Thanks,
Josh
![screenshot from 2018-03-25 16-40-29](https://user-images.githubusercontent.com/25752941/37876948-cd54bfea-304b-11e8-9544-14563604436a.png)
