### ISSUE TITLE
Colour contrast issues with labels

### ISSUE THREAD

**Issue by KramKroc** [AllAboutCode/EduBlocks#35]
*Summary*

Might be my old eyes, but there are contrast issues between the block labels being white and the brighter coloured blocks themselves.

*Steps to Reproduce*
* Launch EduBlocks
* Expand the gpiozero blocks and view the General blocks

*Expected Results*
* Can easily view label and understand what it's purpose is

*Actual results*
* Can't see what the text is and rely on tool tip

gpiozero general is the worst but some others that are hard to view are:

* gpriozero Internal & SPI Devices
* Sonic Pi
* Advanced HttpClient
* Minecraft Commands

*System*
* OS: Raspbian Stretch
* EduBlocks: 1.0.0

**Comment by JoshuaLowe1002** [comment]
Hello there,

Thanks for raising an issue!
You have a very fair point now, I am looking into making the blocks slightly darker and easier to ready and shall get back to you!

Josh

**Comment by KramKroc** [comment]
The colours need to be flatter (https://flatuicolors.com/) @JoshuaLowe1002 I guess. I was looking at the google blocky api and examples and their colours are much flatter. It's a shame that they don't let you define a different colour for the text. But it's odd that the same colour numbers you define in https://github.com/AllAboutCode/EduBlocks/blob/tarball-install/ui/src/blocks/gpiozero/definitions.ts, e.g. 60 for the gpiozero appears much duller in this blocky demo: https://blockly-demo.appspot.com/static/demos/blockfactory/index.html

**Comment by JoshuaLowe1002** [comment]
That's because I have changed a few settings, so it looks different. I will fix it though

**Comment by JoshuaLowe1002** [comment]
Hey @KramKroc, This is fixed now by bigger blocks, bigger and bolder text and we've started to use Flat UI colours. 

I had fixed this just not updated this issue, this will come in the new Scratch Blocks versions.

![image](https://user-images.githubusercontent.com/25752941/47425109-44cf7600-d781-11e8-8b29-2155eb1c84f0.png)

**Comment by KramKroc** [comment]
Awesome @JoshuaLowe1002
