### ISSUE TITLE
LED block doesn't translate to Python

### ISSUE THREAD

**Issue by microbit-mark** [AllAboutCode/EduBlocks#36]
When creating an LED screen example such as:
![screen shot 2018-03-19 at 10 12 36](https://user-images.githubusercontent.com/31242877/37589884-756980e6-2b5e-11e8-819a-21b2833e8e0a.png)
or
![screen shot 2018-03-19 at 10 17 20](https://user-images.githubusercontent.com/31242877/37589985-c50c09f2-2b5e-11e8-9bab-c41965bef284.png)

The python code only registers that one LED on the row is to diplay at the set brightness
![screen shot 2018-03-19 at 10 12 22](https://user-images.githubusercontent.com/31242877/37589894-79a9eb8c-2b5e-11e8-9adb-17b1f072c345.png)

So the resulting program for both blocks is 

![img_20180319_101002](https://user-images.githubusercontent.com/31242877/37590063-f8f3f7ac-2b5e-11e8-923c-0565e3590181.jpg)

This code would give the proper output for 5 LEDs on each row
![screen shot 2018-03-19 at 10 22 45](https://user-images.githubusercontent.com/31242877/37590237-8d9ac926-2b5f-11e8-9f5a-81f676624d48.png)

**Comment by JoshuaLowe1002** [comment]
Hi Mark,
Thanks for leaving an issue.
The next iteration of EduBlocks which features a ton of bug fixes (including this one) is due to be released tonight/tomorrow. I finished testing of the fixes at the weekend. I will be sure to get back to you on this later tonight when it is released!

Thanks,
Josh :)

**Comment by JoshuaLowe1002** [comment]
Hey Mark, it's going to be tomorrow before I push the fix, I hope there is now rush :)

**Comment by microbit-mark** [comment]
No rush. I pointed a python.microbit.org user to edublocks and they found this bug. Glad to hear the fix is already in the pipeline. Great work! 👍 😄

**Comment by JoshuaLowe1002** [comment]
Hey Mark,
I have fixed this bug, and now all boxes set to **0** by default, this means that it will translate to python correctly.

Also, you can now only input numbers into the blocks, with a range of 0-9, so it will stop you putting anything else in there other than certain numbers.

Hope this solves the issue,
Josh

![image](https://user-images.githubusercontent.com/25752941/37876860-e4c50398-304a-11e8-8e94-bbf2545e5476.png)

**Comment by JoshuaLowe1002** [comment]
Still got a bug, need to fix tomorrow

**Comment by JoshuaLowe1002** [comment]
Bug fixed, fully working now! Thank you for your patience!
