### ISSUE TITLE
Sample error

### ISSUE THREAD

**Issue by CathyYarker** [AllAboutCode/EduBlocks#51]
My son is excited about learning Edublocks.  We have put together a raspberry pi 2b with a webcam which defaulted to port 8081.  This first conflicted with running the edublocks after installation because it uses 8081.  I changed the webcam to 8082 and now the edublocks run. 
We ran the 'Disco' sample and received the following error message when we ran it:
in terminal
[Starting]
Traceback (most recent call last):
File "/home/pi/.edublocks/output.py", line 146, in <module>
  global mc; mc = Minecraft.create()
File "/usr/lib/python3/dist-packages/mcpi/minecraft.py", Line 171, in create
  return Minecraft(Connection(address,port))
File "/usr/lib/python3/dist-packages/mcpi/connection.py", line 17, in __init__
  selft.socket.connect((address, port))
ConnectionRefusedError: [Errno 111] connection refused.

Any guidance would be appreciated.

**Comment by titimoby** [comment]
Maybe check the address and port of minecraft running server.

**Comment by JoshuaLowe1002** [comment]
Hey Cathy,

Great news about your Son eager to learn!

You need to launch 2 programs for the disco sample to work.

The first one is found in the Raspberry Pi Menu > Programming > Sonic Pi. You'll need sound for this.

The second one is found in the Raspberry Pi Menu > Games > Minecraft Pi. Select New Game and Create New.

This should work.

**Comment by JoshuaLowe1002** [comment]
Correct @titimoby , nothing is running on the port because Minecraft is not loaded :)

**Comment by CathyYarker** [comment]
Very newbie question.  Thank you so much for your help!  This can be closed.

**Comment by JoshuaLowe1002** [comment]
No worries, glad we could hall. Thanks to @titimoby for jumping in on this one too. 

Hope you enjoy EduBlocks. Let me know what you get up to

**Comment by titimoby** [comment]
I'll be glad to answer any question on Edublocks, but github issues is not very beginner friendly

**Comment by JoshuaLowe1002** [comment]
No, agreed, we do have a community forum, but it's not public, maybe this would be a good idea? @titimoby

**Comment by titimoby** [comment]
Let's say an easy place for beginner may be a good idea
