### ISSUE TITLE
Raspberry Pi 1 support (ARMv6)

### ISSUE THREAD

**Issue by gbaman** [AllAboutCode/EduBlocks#6]
Edublocks fails to run on a Raspberry Pi 1 model B or model B+, or Pi Zeros. This is due to the fact that they use the ARMv6 architecture and the deb.nodesource.com repo used for a newer version of NodeJS only includes ARMv7 and beyond.
Given the very significant number of Pi1s out in the wild (plus Pi Zeros), it would be great to have EduBlocks support it as well for the older processor used in Pi 1s or Pi Zero.

Is there any upcoming plans for this?

**Comment by JoshuaLowe1002** [comment]
Hi Andrew,
Yes we do have plans to look into this, and soon. It is a major problem that was brought up a couple of weeks back and it is our main priority to fix this Sunday when we are fixing issues.

Thanks,
Josh
EduBlocks Dev Team

**Comment by JoshuaLowe1002** [comment]
Fixed in new BETA version coming soon

**Comment by gbaman** [comment]
Fantastic, glad to hear it. Are you using a different source for Node or bundling it with it?

**Comment by JoshuaLowe1002** [comment]
Added in new version: curl -sSL get.edublocks.org | bash
