### ISSUE TITLE
Add a method for users to install any Python library

### ISSUE THREAD

**Issue by lesp** [AllAboutCode/EduBlocks#7]
Hello, great work on the project!

May I suggest a method so that users can install any Python 3 library using the Edublocks interface?
This could be a simple wrapper around pip3 that handles installation and dependencies.

The problem we face will be the creation of the blocks in EduBlocks. Could the application handle creating the menu and blocks on the fly?

Thanks :D

**Comment by JoshuaLowe1002** [comment]
Due to limitations in blockly, this is not possible right now.
