### ISSUE TITLE
How to add comments - Microbit beta

### ISSUE THREAD

**Issue by DarrenTownsend** [AllAboutCode/EduBlocks#74]
Testing out the new Microbit web editor but I can't see how to add a comment to the code. Is it me?

**Comment by JoshuaLowe1002** [comment]
Hey Darren @DarrenTownsend , 

Are you trying to add a comment to a block or add a workspace comment?

**Comment by JoshuaLowe1002** [comment]
If you're doing a workspace comment (the one I mention in the Patreon update), then you right click and select "Add comment". 
![add-workspace-comment](https://user-images.githubusercontent.com/25752941/50056519-397f4200-0155-11e9-95dc-580ef81c7df6.gif)

**Comment by JoshuaLowe1002** [comment]
If you wanted to add a comment to a block and then have that show up in the python code as a hash comment, then you can right click on the block and select "Add Comment" 
![add-block-comment](https://user-images.githubusercontent.com/25752941/50056532-70edee80-0155-11e9-989f-d7fd4e35e27f.gif)
