### ISSUE TITLE
Suggestion to add a hint to Image block in Microbit.

### ISSUE THREAD

**Issue by Eskibrew** [AllAboutCode/EduBlocks#77]
Image block does not currently have a popup hint. I'd suggest adding a hint which explains that the values entered into each pixel can be 0 to 9 with zero being off and 9 being full brightness.

**Comment by JoshuaLowe1002** [comment]
Fixed here: https://github.com/AllAboutCode/EduBlocks/commit/220920c41fecb74b3c78d5a1ae06eb93f093369c

Thanks for bringing this up
