### ISSUE TITLE
server has dependency on "node": "^6.10.3": is this version really mandatory?

### ISSUE THREAD

**Issue by titimoby** [AllAboutCode/EduBlocks#78]
I just saw that server depends on node 6.10.3
Is it still the accurate version ?

I tested the dev version on my ubuntu and everything looks smooth with 8.15.0

**Comment by JoshuaLowe1002** [comment]
Hey!

I'll have a test this weekend and update to that if all is good

**Comment by JoshuaLowe1002** [comment]
Forgot about this one, unfortunately this is due to the outdated node version on the Pi and is required
