### ISSUE TITLE
Allow installation as root

### ISSUE THREAD

**Issue by maxnet** [AllAboutCode/EduBlocks#80]
It would be nice if your installation script did allow itself to be executed as the root user.
On multi-user systems (e.g. piserver setups) installing software globally as root is the only option.
No pi user there.

Other than that you will not be able to put an icon on the user's desktop, I don't think there is any disadvantage on allowing root installations either.

**Comment by JoshuaLowe1002** [comment]
Hey!

I have actually come across this problem myself.
Let me take a look at this and see if I can make it run with root
