### ISSUE TITLE
Please consider using the Mastodon social network instead of/in addition to Twitter

### ISSUE THREAD

**Issue by MagicFab** [AllAboutCode/EduBlocks#82]
I'd like to suggest EduBlocks contributors use the Mastodon social network to share their work progress and other information instead of or at least in addition to Twitter.

* [What is Mastodon and why should I use it ?](https://laurakalbag.com/what-is-mastodon-and-why-should-i-use-it/) also has useful information on other aspects of using Mastodon

* https://instances.social/ can help choose which instance to register a new account on. 

* Normally it's encouraged to use individual accounts, not project accounts. For a personal account, I would suggest [Fosstodon](https://fosstodon.org/about) ot https://mastodon.social/about . Also see [The Importance of Choosing the Correct Mastodon Instance](https://carlchenet.com/the-importance-of-choosing-the-correct-mastodon-instance/) 

Thanks in advance for considering this suggestion.

**Comment by JoshuaLowe1002** [comment]
Having considered it, Mastodon is not reaching our target audience therefore I've decided not to setup and account. Thanks for the suggestion though
