### ISSUE TITLE
Readme.md: "Linux Install Instructions" need an update

### ISSUE THREAD

**Issue by titimoby** [AllAboutCode/EduBlocks#84]
In the Readme.md, line 98 in the "Linux Install Instructions"
`ln -s ../../server/src/protocol.ts src/protocol.ts
`

but doing this on a fresh clone results in:
`ln: failed to create symbolic link 'src/protocol.ts': File exists`

Nothing to do here, link exists.
Just needs to remove that line I think.

**Comment by JoshuaLowe1002** [comment]
Fixed!
