### ISSUE TITLE
Issues installing on Raspi

### ISSUE THREAD

**Issue by QuadDam** [AllAboutCode/EduBlocks#96]
![IMG_5005](https://user-images.githubusercontent.com/27566959/64444200-721acf00-d088-11e9-9924-e21756250b4b.JPG)
I am trying to install Edubocks using the terminal but I am getting this error, any help would be great, thanks!

**Comment by JoshuaLowe1002** [comment]
Hi! Please try again, might have fixed it @QuadDam

**Comment by QuadDam** [comment]
Thanks so much I will Monday
